# Generated by Django 3.1.12 on 2025-04-15 05:32

import bson.objectid
import dashboard.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contacts', djongo.models.fields.JSONField()),
                ('emergency_contact', djongo.models.fields.JSONField()),
                ('vitals', djongo.models.fields.ArrayField(model_container=dashboard.models.Vitals)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
    ]
