# Generated by Django 3.1.12 on 2025-05-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(default='Not Specified', max_length=10),
        ),
    ]
