# Generated by Django 3.1.12 on 2025-07-08 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_patient_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
