
SPO2_CRITICAL_THRESHOLD = 90
SPO2_CAUTION_THRESHOLD = 95


WEIGHT_DAILY_INCREASE_CRITICAL_KG = 3


HR_NORMAL_MIN = 60
HR_NORMAL_MAX = 100


# Normal BP
BP_NORMAL_SYSTOLIC_MAX = 119
BP_NORMAL_DIASTOLIC_MAX = 79

# Elevated BP
BP_ELEVATED_SYSTOLIC_MIN = 120
BP_ELEVATED_SYSTOLIC_MAX = 129
BP_ELEVATED_DIASTOLIC_MAX = 79 # Diastolic must be < 80 for Elevated

# Stage 1 Hypertension
BP_STAGE1_SYSTOLIC_MIN = 130
BP_STAGE1_SYSTOLIC_MAX = 139
BP_STAGE1_DIASTOLIC_MIN = 80
BP_STAGE1_DIASTOLIC_MAX = 89

# Stage 2 Hypertension (Critical/High)
BP_STAGE2_SYSTOLIC_MIN = 140
BP_STAGE2_DIASTOLIC_MIN = 90